global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: backend
    metrics_path: /metrics
    static_configs:
      - targets:
          - backend_1:8000
          - backend_2:8000

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: etcd
    metrics_path: /metrics
    static_configs:
      - targets: ["etcd:2379"]

  - job_name: patroni
    metrics_path: /metrics
    static_configs:
      - targets:
          - patroni_1:8008
          - patroni_2:8008

  - job_name: blackbox-http
    metrics_path: /probe
    params:
      module: ["http_2xx"]
    static_configs:
      - targets:
          - http://frontend_1:80/
          - http://frontend_2:80/
          - http://haproxy_1:80/
          - http://haproxy_2:80/
          - http://patroni_1:8008/health
          - http://patroni_2:8008/health
          - http://etcd:2379/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  - job_name: blackbox-tcp
    metrics_path: /probe
    params:
      module: ["tcp_connect"]
    static_configs:
      - targets:
          - haproxy_db_1:5432
          - haproxy_db_2:5432
          - pgpool_1:5432
          - pgpool_2:5432
          - patroni_1:5432
          - patroni_2:5432
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
